# Generated by Django 4.1.7 on 2023-04-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='nsme',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='character',
            name='luck',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='character',
            name='magic',
            field=models.IntegerField(default=10),
        ),
    ]
